### ISSUE TITLE
Consider masking passwords in URIs

### ISSUE THREAD

**Issue by ahmet2mir** [rabbitmq/rabbitmq-federation-management#15]
In **Federation Upstreams** when a password is set on a broker `amqps://user:password@mybroker`, it's visible on the web page. So it's more confidential to hide it.

**Comment by michaelklishin** [comment]
How would the administrator then know what the actual password is?

**Comment by michaelklishin** [comment]
This is an example of security and usability being at odds. Perhaps a link that has to be clicked  for the entire URL to be displayed would be an easy and secure enough solution?

**Comment by ahmet2mir** [comment]
As an admin I could create the federation etc.
I could allow some user in some

**Comment by ahmet2mir** [comment]
Generally, it's a "good practice" to never show passwords.
And of course, `rabbitmqctl list_parameters -p myvhost` returns the password, but an access to the server is needed.

**Comment by michaelklishin** [comment]
@ahmet2mir I don't think the "good practice" argument is sufficient to convince our team. There are exceptions and fine nuances to every "good practice." We need to balance two things:

 * Security
 * Ease of discovering the password

This plugin should already limit access to the users that are tagged as `policymaker`. This alone should prevent most users from ever seeing the list of links. Have you taken this into account?

Most users are not aware of the fact that federation upstreams and other data are stored as runtime parameters. Some users do not have access to `rabbitmqctl` at all (RabbitMQ can be offered as a service).

I certainly understand the argument that it is desirable to not reveal passwords by default. However not revealing them at all or making it really hard to discover would also suck.

**Comment by ahmet2mir** [comment]
I understand the ease of discovering the password, but if in the openspace, I open the tab just to see the config, somebody (not allowed) could see the password (Security from shoulder surfing).
If I wan't to show the password, I ssh the broker and run rabbitqctl list_parmaters (and I think that the URI must be hide in the output too).
That's why I put "good practice" in quotes.

**Comment by michaelklishin** [comment]
@ahmet2mir I stated above that not everyone can "ssh the broker."

So, what options do we have? We cannot just mask or not show the password in the URI. Revealing credentials after a link is clicked is the best idea I have right now.

**Comment by essen** [comment]
It's not a bad idea. My company's bank is doing this for initial passwords (granted these passwords are only used to define your own password later on, but still, they're never shown without you doing a mouse hover/click).

Ideal is probably to send it as a JS variable (so it's not displayed before the CSS is loaded) and have a small JS snippet to show it when the user asks.

**Comment by dcorbacho** [comment]
The proposed PRs use mouse hover to show the URIs, as a hide/show button requires a more complex implementation using cookies to maintain state. Otherwise, by using buttons, on every refresh (5s) the URIs are hidden again (upstreams list).

**Comment by michaelklishin** [comment]
We experimented with a couple of prototypes and so far masking (or stripping) the credentials is the right (and easiest) thing to do.
