### ISSUE TITLE
Introduce an API endpoint that lists problematic links

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-federation-management#18]
By "problematic" we mean "in a state other than Running."

Related to https://github.com/rabbitmq/rabbitmq-federation/issues/43 and #17.

**Comment by uvzubovs** [comment]
Doesn't /api/federation-links return all links whether running or not?

**Comment by michaelklishin** [comment]
@uvzubovs it does. This issue is about introducing a separate endpoint that would only list down nodes.
