### ISSUE TITLE
Add a form input for the "exchange" option

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-federation-management#5]
See [upstream parameters reference](http://www.rabbitmq.com/federation-reference.html). Note that it only applies to exchange federation so we may need to reconsider certain UI decisions on that form as some fields will be federation "type"-specific.

**Comment by uvzubovs** [comment]
This is kind of important as we run RabbitMQ in PCF, and cannot quite run rabbitmqctl without major rigmarole. There also does not seem to be a management API (REST) to define the federation upstream, or is there?

**Comment by michaelklishin** [comment]
Parameters and policies can be defined [using HTTP API](https://raw.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_0/priv/www/api/index.html).

**Comment by uvzubovs** [comment]
Are you saying that although there is no API to create the upstream, it can be created via GUI and then "exchange" parameter may be added to an existing upstream component using PUT to /api/parameters? Or, is there an API to create the upstream?

By the way, can /api/parameters be used to modify a queue attribute, like add dead letter exchange without re-creating the queue? 

Thanks!

**Comment by michaelklishin** [comment]
@uvzubovs if management UI has a feature, then HTTP API has it as well. There is a way to create an upstream in the API because upstreams are set up using parameters. Parameters do not modify anything, they are a cluster-wide key-value store of sorts. Policies do and they are just one specific case of how parameters are used.

Sorry but we do not use issues for general user support. Please route your questions to rabbitmq-users.

**Comment by michaelklishin** [comment]
Fixed in #6.
